### ISSUE TITLE
在 easy-monitor 分析 CPU Profile 的时候前端崩溃

### ISSUE THREAD

**Issue by yunnysunny** [X-Profiler/xprofiler-console#37]
点击转储后的 CPU Profile 的分析按钮，前端就报错了：
```
chunk-vendors.8e038e6d.js:12 TypeError: Cannot read properties of undefined (reading 'functionName')
    at Function.value (app.3553e238.js:1:306707)
    at e.value (app.3553e238.js:1:305195)
    at e.value (app.3553e238.js:1:306477)
    at Am (app.3553e238.js:1:307791)
    at s.customData (app.3553e238.js:1:308985)
    at nr.get (chunk-vendors.8e038e6d.js:12:30685)
    at nr.evaluate (chunk-vendors.8e038e6d.js:12:31686)
    at s.customData (chunk-vendors.8e038e6d.js:12:33379)
    at s.Pm (app.3553e238.js:1:304092)
    at s.e._render (chunk-vendors.8e038e6d.js:12:23734)
```

**Comment by hyj1991** [comment]
升级下控制台到最新，cpuprofile 格式现在用了最新的 devtools 序列化格式
